version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm run install
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - node_modules
            - package-lock.json
      - run:
          name: build
          command: npm run build
workflows:
  version: 2
  build:
    jobs:
      - build
