// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client/index.js';
import type { GetCurrentUserProfileData, GetCurrentUserProfileResponses, GetPublicUserProfilesData, GetPublicUserProfilesResponses, GetPermissionsData, GetPermissionsResponses, GetExchangeRateData, GetExchangeRateResponses, GetDepositAddressData, GetDepositAddressResponses, GetBalancesData, GetBalancesResponses, GetSpendableBalancesData, GetSpendableBalancesResponses, PayData, PayResponses, GetPaymentDetailsData, GetPaymentDetailsResponses, GetItemsInventoryData, GetItemsInventoryResponses, GetPaymentRequestsData, GetPaymentRequestsResponses, CreatePaymentRequestData, CreatePaymentRequestResponses, DeletePaymentRequestData, DeletePaymentRequestResponses, GetPaymentRequestData, GetPaymentRequestResponses, UpdatePaymentRequestData, UpdatePaymentRequestResponses, GetPaymentRequestsPublicInfoData, GetPaymentRequestsPublicInfoResponses, GetPaymentRequestsPublicStatsData, GetPaymentRequestsPublicStatsResponses, GetItemCreationOrderData, GetItemCreationOrderResponses, GetItemsData, GetItemsResponses, CreateItemCreationOrderData, CreateItemCreationOrderResponses, AddItemsToItemCreationOrderData, AddItemsToItemCreationOrderResponses, CommitItemCreationOrderData, CommitItemCreationOrderResponses, CreateBatchData, CreateBatchResponses, IssueItemsData, IssueItemsResponses, BurnAndCreateData, BurnAndCreateResponses } from './types.gen.js';
import { client as _heyApiClient } from './client.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Connect {
    /**
     * Get a current user profile
     */
    public static getCurrentUserProfile<ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserProfileData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetCurrentUserProfileResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/connect/profile/currentUserProfile',
            ...options
        });
    }
    
    /**
     * Get user profiles
     */
    public static getPublicUserProfiles<ThrowOnError extends boolean = false>(options: Options<GetPublicUserProfilesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetPublicUserProfilesResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/connect/profile/publicUserProfiles',
            ...options
        });
    }
    
    /**
     * Get users permissions
     */
    public static getPermissions<ThrowOnError extends boolean = false>(options?: Options<GetPermissionsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetPermissionsResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/connect/profile/permissions',
            ...options
        });
    }
    
    /**
     * Retrieve the BSV exchange rate in the specified currency.
     */
    public static getExchangeRate<ThrowOnError extends boolean = false>(options: Options<GetExchangeRateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetExchangeRateResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/connect/exchangeRate/{currencyCode}',
            ...options
        });
    }
    
    /**
     * Get a legacy deposit address
     */
    public static getDepositAddress<ThrowOnError extends boolean = false>(options?: Options<GetDepositAddressData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetDepositAddressResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/connect/wallet/address',
            ...options
        });
    }
    
    /**
     * Retrieve wallet balances.
     */
    public static getBalances<ThrowOnError extends boolean = false>(options?: Options<GetBalancesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetBalancesResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/connect/wallet/balances',
            ...options
        });
    }
    
    /**
     * Retrieve wallets spendable balances.
     */
    public static getSpendableBalances<ThrowOnError extends boolean = false>(options?: Options<GetSpendableBalancesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetSpendableBalancesResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/connect/wallet/spendableBalances',
            ...options
        });
    }
    
    /**
     * Make a payment
     */
    public static pay<ThrowOnError extends boolean = false>(options: Options<PayData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PayResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/connect/wallet/pay',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Retrieve details for a specific payment.
     */
    public static getPaymentDetails<ThrowOnError extends boolean = false>(options: Options<GetPaymentDetailsData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetPaymentDetailsResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/connect/wallet/payment',
            ...options
        });
    }
    
    /**
     * Get items inventory
     */
    public static getItemsInventory<ThrowOnError extends boolean = false>(options: Options<GetItemsInventoryData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<GetItemsInventoryResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/connect/items/inventory',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class PaymentRequests {
    /**
     * Get all payment requests for the app.
     */
    public static getPaymentRequests<ThrowOnError extends boolean = false>(options?: Options<GetPaymentRequestsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetPaymentRequestsResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/paymentRequests/',
            ...options
        });
    }
    
    /**
     * Create a new payment request.
     */
    public static createPaymentRequest<ThrowOnError extends boolean = false>(options: Options<CreatePaymentRequestData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreatePaymentRequestResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/paymentRequests/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete a payment requests
     */
    public static deletePaymentRequest<ThrowOnError extends boolean = false>(options: Options<DeletePaymentRequestData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeletePaymentRequestResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/paymentRequests/{id}',
            ...options
        });
    }
    
    /**
     * Get a payment requests with private info
     */
    public static getPaymentRequest<ThrowOnError extends boolean = false>(options: Options<GetPaymentRequestData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetPaymentRequestResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/paymentRequests/{id}',
            ...options
        });
    }
    
    /**
     * Edit a payment requests
     */
    public static updatePaymentRequest<ThrowOnError extends boolean = false>(options: Options<UpdatePaymentRequestData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<UpdatePaymentRequestResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/paymentRequests/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get a payment requests with public info
     */
    public static getPaymentRequestsPublicInfo<ThrowOnError extends boolean = false>(options: Options<GetPaymentRequestsPublicInfoData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetPaymentRequestsPublicInfoResponses, unknown, ThrowOnError>({
            url: '/v3/paymentRequests/public/{id}',
            ...options
        });
    }
    
    /**
     * Get a payment requests public stats info
     */
    public static getPaymentRequestsPublicStats<ThrowOnError extends boolean = false>(options: Options<GetPaymentRequestsPublicStatsData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetPaymentRequestsPublicStatsResponses, unknown, ThrowOnError>({
            url: '/v3/paymentRequests/public/stats/{id}',
            ...options
        });
    }
}

export class Minter {
    /**
     * Retrieve details for a specific item creation order.
     */
    public static getItemCreationOrder<ThrowOnError extends boolean = false>(options: Options<GetItemCreationOrderData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetItemCreationOrderResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                }
            ],
            url: '/v3/itemCreationOrder/{itemCreationOrderId}',
            ...options
        });
    }
    
    /**
     * Retrieve items associated with a specific item creation order.
     */
    public static getItems<ThrowOnError extends boolean = false>(options: Options<GetItemsData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetItemsResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                }
            ],
            url: '/v3/itemCreationOrder/{itemCreationOrderId}/items',
            ...options
        });
    }
    
    /**
     * Issue items for a creation order.
     */
    public static createItemCreationOrder<ThrowOnError extends boolean = false>(options: Options<CreateItemCreationOrderData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateItemCreationOrderResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                }
            ],
            url: '/v3/itemCreationOrder/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Add items to a creation order.
     */
    public static addItemsToItemCreationOrder<ThrowOnError extends boolean = false>(options: Options<AddItemsToItemCreationOrderData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<AddItemsToItemCreationOrderResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                }
            ],
            url: '/v3/itemCreationOrder/{itemCreationOrderId}/add',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Commit items creation order.
     */
    public static commitItemCreationOrder<ThrowOnError extends boolean = false>(options: Options<CommitItemCreationOrderData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CommitItemCreationOrderResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                }
            ],
            url: '/v3/itemCreationOrder/{itemCreationOrderId}/commit',
            ...options
        });
    }
    
    /**
     * Mint next batch of items.
     */
    public static createBatch<ThrowOnError extends boolean = false>(options: Options<CreateBatchData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateBatchResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                }
            ],
            url: '/v3/itemCreationOrder/createBatch',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Issue items for a creation order.
     */
    public static issueItems<ThrowOnError extends boolean = false>(options: Options<IssueItemsData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<IssueItemsResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                }
            ],
            url: '/v3/itemCreationOrder/issueItems',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Burn and create new items in a single operation - crafting.
     */
    public static burnAndCreate<ThrowOnError extends boolean = false>(options: Options<BurnAndCreateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<BurnAndCreateResponses, unknown, ThrowOnError>({
            security: [
                {
                    name: 'oauth-publickey',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-signature',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-nonce',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-timestamp',
                    type: 'apiKey'
                },
                {
                    name: 'oauth-privatekey',
                    type: 'apiKey'
                },
                {
                    name: 'app-id',
                    type: 'apiKey'
                },
                {
                    name: 'app-secret',
                    type: 'apiKey'
                }
            ],
            url: '/v3/itemCreationOrder/burnAndCreate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}