// This file is auto-generated by @hey-api/openapi-ts

export type AccountFullPublicProfilesSchema = {
    items: Array<{
        id: string;
        handle: string;
        paymail: string;
        displayName?: string;
        avatarUrl?: string;
        localCurrencyCode: string;
        /**
         * @deprecated
         */
        bitcoinUnit?: string;
        createdAt: string;
    }>;
};

export type AccountFullUserProfileSchema = {
    publicProfile?: {
        id: string;
        handle: string;
        paymail: string;
        displayName?: string;
        avatarUrl?: string;
        localCurrencyCode: string;
        /**
         * @deprecated
         */
        bitcoinUnit?: string;
        createdAt: string;
    };
    privateProfile?: {
        email?: string;
        /**
         * @deprecated
         */
        phoneNumber?: '';
    };
};

export type AccountProfileApiDefinition = {
    alias: string;
    displayName?: string;
    profilePictureUrl?: string;
    id?: string;
};

export type AccountProfilesSchema = {
    items: Array<{
        alias: string;
        displayName?: string;
        profilePictureUrl?: string;
        id?: string;
    }>;
};

export type ApplicationApplicationsSchema = {
    items: Array<{
        id: string;
        name: string;
        longDescription?: string;
        shortDescription?: string;
        iconUrl?: string;
        bannerUrl?: string;
        publisherEmail?: string;
        appWebsiteUrl?: string;
        appAndroidUrl?: string;
        appAppleUrl?: string;
        privacyPolicyUrl?: string;
        screenUrls: Array<string>;
        permissions?: Array<'USER_PRIVATE_PROFILE' | 'USER_PUBLIC_PROFILE' | 'PAY' | 'FRIENDS' | 'DECRYPT' | 'SIGN_DATA' | 'OWNERSHIP' | 'ITEMS_READ' | 'ITEMS_WRITE' | 'READ_BALANCE' | 'READ_TRANSACTIONS' | 'GENERATE_ADDRESS' | 'ITEM_ISSUE' | 'DEVICE_ADMIN' | 'SIGNUP'>;
        authenticationSuccessUrl?: string;
        authenticationDeclineUrl?: string;
        isUserConnected: boolean;
        hasShopItems: boolean;
        isAppExtension: boolean;
        isPromotedOnMarket: boolean;
        isFeaturedOnMarket: boolean;
        extensions: Array<{
            id: string;
            name?: string;
            iconUrl?: string;
            authorizationSuccessWebhook?: string;
            permissions?: Array<string>;
        }>;
    }>;
};

export type ConnectPermissionsSchema = {
    items: Array<'USER_PRIVATE_PROFILE' | 'USER_PUBLIC_PROFILE' | 'PAY' | 'READ_BALANCE' | 'GENERATE_ADDRESS' | 'READ_TRANSACTIONS' | 'ITEMS_READ' | 'ITEMS_WRITE'>;
    appId: string;
};

export type ItemsCollectionSchema = {
    id: string;
    isFeatured: boolean;
    origin: string;
    name: string;
    attributes?: Array<{
        [key: string]: unknown;
    }>;
    description: string;
    imageUrl: string;
    totalQuantity: number;
    isHandcashCreated: boolean;
    isVerified: boolean;
    isVisibleInMarket: boolean;
    app?: {
        id: string;
        name?: string;
        iconUrl?: string;
    };
};

export type ItemsCollectionsSchema = {
    featured?: Array<{
        id: string;
        isFeatured: boolean;
        origin: string;
        name: string;
        attributes?: Array<{
            [key: string]: unknown;
        }>;
        description: string;
        imageUrl: string;
        totalQuantity: number;
        isHandcashCreated: boolean;
        isVerified: boolean;
        isVisibleInMarket: boolean;
        app?: {
            id: string;
            name?: string;
            iconUrl?: string;
        };
    }>;
    others?: Array<{
        id: string;
        isFeatured: boolean;
        origin: string;
        name: string;
        attributes?: Array<{
            [key: string]: unknown;
        }>;
        description: string;
        imageUrl: string;
        totalQuantity: number;
        isHandcashCreated: boolean;
        isVerified: boolean;
        isVisibleInMarket: boolean;
        app?: {
            id: string;
            name?: string;
            iconUrl?: string;
        };
    }>;
};

export type ItemsItemCreationOrderSchema = {
    id: string;
    user: string;
    app: string;
    referencedCollection?: string;
    type: string;
    status: string;
    pendingInscriptions: number;
    error?: string;
};

export type ItemsItemMetricsSchema = {
    itemsSold: number;
    volumeInUSD: number;
    numberOfActiveListings: number;
    numberOfOwners: number;
    supply: number;
};

export type ItemsItemSchema = {
    id: string;
    origin?: string;
    user?: {
        id: string;
        alias: string;
        displayName: string;
        profilePictureUrl: string;
    };
    collection?: {
        id: string;
        isFeatured: boolean;
        origin: string;
        name: string;
        attributes?: Array<{
            [key: string]: unknown;
        }>;
        description: string;
        imageUrl: string;
        totalQuantity: number;
        isHandcashCreated: boolean;
        isVerified: boolean;
        isVisibleInMarket: boolean;
        app?: {
            id: string;
            name?: string;
            iconUrl?: string;
        };
    } | {
        id?: string;
    };
    app?: {
        id: string;
        name?: string;
        iconUrl?: string;
    };
    name: string;
    groupingValue: string;
    description: string;
    imageUrl: string;
    multimediaUrl: string;
    multimediaType: string;
    rarity: string;
    color: string;
    attributes?: Array<{
        name: string;
        value?: string | number;
        displayType: string;
    }>;
    isHandcashCreated: boolean;
    isVerified: boolean;
    isListing: boolean;
    itemListing?: {
        id: string;
        status: string;
        paymentRequestUrl: string;
        paymentRequestId: string;
        price: number;
        currencyCode: string;
        denominatedIn: string;
        fiatEquivalent?: {
            amount: number;
            currencyCode: string;
        };
        listedAt: string;
    };
    count: number;
    royalties?: Array<{
        type: string;
        percentage: number;
        destination: string;
    }>;
    actions?: Array<{
        name: string;
        description: string;
        url: string;
        enabled: boolean;
    }>;
    isCurrentUser: boolean;
    floorPriceInUsd?: number;
    lastSoldPriceInUsd?: number;
    externalId?: string;
    priceAlert?: {
        amountInUSD: number;
        groupingValue: string;
        itemName: string;
        contentUrl: string;
        collectionName: string;
        appName: string;
        active?: boolean;
    };
};

export type ItemsItemsSchema = {
    items?: Array<{
        id: string;
        origin?: string;
        user?: {
            id: string;
            alias: string;
            displayName: string;
            profilePictureUrl: string;
        };
        collection?: {
            id: string;
            isFeatured: boolean;
            origin: string;
            name: string;
            attributes?: Array<{
                [key: string]: unknown;
            }>;
            description: string;
            imageUrl: string;
            totalQuantity: number;
            isHandcashCreated: boolean;
            isVerified: boolean;
            isVisibleInMarket: boolean;
            app?: {
                id: string;
                name?: string;
                iconUrl?: string;
            };
        } | {
            id?: string;
        };
        app?: {
            id: string;
            name?: string;
            iconUrl?: string;
        };
        name: string;
        groupingValue: string;
        description: string;
        imageUrl: string;
        multimediaUrl: string;
        multimediaType: string;
        rarity: string;
        color: string;
        attributes?: Array<{
            name: string;
            value?: string | number;
            displayType: string;
        }>;
        isHandcashCreated: boolean;
        isVerified: boolean;
        isListing: boolean;
        itemListing?: {
            id: string;
            status: string;
            paymentRequestUrl: string;
            paymentRequestId: string;
            price: number;
            currencyCode: string;
            denominatedIn: string;
            fiatEquivalent?: {
                amount: number;
                currencyCode: string;
            };
            listedAt: string;
        };
        count: number;
        royalties?: Array<{
            type: string;
            percentage: number;
            destination: string;
        }>;
        actions?: Array<{
            name: string;
            description: string;
            url: string;
            enabled: boolean;
        }>;
        isCurrentUser: boolean;
        floorPriceInUsd?: number;
        lastSoldPriceInUsd?: number;
        externalId?: string;
        priceAlert?: {
            amountInUSD: number;
            groupingValue: string;
            itemName: string;
            contentUrl: string;
            collectionName: string;
            appName: string;
            active?: boolean;
        };
    }>;
};

export type ItemsItemStatsSchema = {
    listingsCount: number;
    itemsCount: number;
};

export type ItemsItemTradeHistorySchema = {
    items?: Array<{
        date: string;
        totalVolumeInUSD: number;
        averagePriceInUSD: number;
    }>;
};

export type ItemsItemTransferSchema = {
    items?: Array<{
        itemName?: string;
        collectionName?: string;
        contentUrl?: string;
        operation: string;
        origin: string;
        groupingValue: string;
        amountInUSD?: number;
        paymentTransactionId?: string;
        createdAt: string;
        participant: {
            [key: string]: never;
        };
    }>;
};

export type MiscExchangeRateSchema = {
    exchangeRateVersion: string;
    rate: number;
    fiatSymbol: string;
    estimatedExpireDate: string;
};

export type PaymentRequestPaymentRequestSchema = {
    id: string;
    paymentRequestUrl: string;
    paymentRequestQrCodeUrl: string;
    status: string;
    transactionId?: string;
    redirectUrl: string;
    expiresAt: string;
    enabledAt?: string;
    product: {
        name: string;
        description?: string;
        longDescription?: string;
        imageUrl: string;
    };
    paymentAmount: {
        currencyCode: string;
        amount: number;
        denominatedIn: string;
    };
    paymentsCount?: number;
    shop?: {
        collectionId: string;
        packOrder: number;
        collectionOrder: number;
        appId: string;
    };
    totalUnits?: number;
    remainingUnits?: number;
    priceBeforeDiscount?: number;
};

export type PaymentRequestPaymentRequestStatsSchema = {
    totalPayments: number;
    totalVolume: number;
    uniqueUsers: number;
};

export type PaymentRequestPrivatePaymentRequestSchema = {
    id: string;
    paymentRequestUrl: string;
    paymentRequestQrCodeUrl: string;
    isEnabled: boolean;
    product: {
        name: string;
        description?: string;
        longDescription?: string;
        imageUrl?: string;
    };
    currencyCode: string;
    receivers: Array<{
        sendAmount: number;
        destination: string;
    }>;
    totalUnits?: number;
    remainingUnits?: number;
    priceBeforeDiscount?: number;
    paymentAmount: {
        currencyCode: string;
        amount: number;
        denominatedIn: string;
    };
    notifications?: {
        webhook?: {
            webhookUrl?: string;
            customParameters?: {
                [key: string]: never;
            };
        };
        email?: string;
    };
    shop?: {
        collectionId: string;
        packOrder: number;
        collectionOrder: number;
        appId: string;
    };
    requestedUserData?: Array<string>;
    redirectUrl?: string;
    expiresAt: string;
    createdAt: string;
    enabledAt: string;
};

export type PaymentRequestPrivatePaymentRequestsSchema = {
    items: Array<{
        id: string;
        paymentRequestUrl: string;
        paymentRequestQrCodeUrl: string;
        isEnabled: boolean;
        product: {
            name: string;
            description?: string;
            longDescription?: string;
            imageUrl?: string;
        };
        currencyCode: string;
        receivers: Array<{
            sendAmount: number;
            destination: string;
        }>;
        totalUnits?: number;
        remainingUnits?: number;
        priceBeforeDiscount?: number;
        paymentAmount: {
            currencyCode: string;
            amount: number;
            denominatedIn: string;
        };
        notifications?: {
            webhook?: {
                webhookUrl?: string;
                customParameters?: {
                    [key: string]: never;
                };
            };
            email?: string;
        };
        shop?: {
            collectionId: string;
            packOrder: number;
            collectionOrder: number;
            appId: string;
        };
        requestedUserData?: Array<string>;
        redirectUrl?: string;
        expiresAt: string;
        createdAt: string;
        enabledAt: string;
    }>;
};

export type WalletAddressSchema = {
    base58Address: string;
    publicKey?: string;
};

export type WalletBalancesSchema = {
    items?: Array<{
        currency?: {
            code: string;
            logoUrl: string;
            symbol: string;
        };
        units: number;
        fiatEquivalent?: {
            currencyCode: string;
            units: number;
        };
    }>;
};

export type WalletSpendableBalancesSchema = {
    items?: Array<{
        spendableBalance: number;
        currencyCode: string;
    }>;
};

export type WalletTransactionRecordSchema = {
    transactionId: string;
    type: string;
    time: number;
    note: string;
    currency?: {
        code: string;
        logoUrl: string;
        symbol: string;
    };
    units: number;
    satoshiFees: number;
    fiatEquivalent?: {
        currencyCode: string;
        units: number;
    };
    participants?: Array<{
        id: string;
        type: string;
        alias?: string;
        displayName: string;
        profilePictureUrl: string;
        responseNote: string;
        tags?: Array<string>;
    }>;
    attachments?: Array<{
        format: string;
        value: unknown;
    }>;
    app?: {
        name: string;
        iconUrl: string;
    };
    item?: {
        imageUrl: string;
        name: string;
        collectionName: string;
        origin: string;
        groupingValue: string;
    };
};

export type GetCurrentUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/connect/profile/currentUserProfile';
};

export type GetCurrentUserProfileResponses = {
    /**
     * OK
     */
    200: AccountFullUserProfileSchema;
};

export type GetCurrentUserProfileResponse = GetCurrentUserProfileResponses[keyof GetCurrentUserProfileResponses];

export type GetPublicUserProfilesData = {
    body?: never;
    path?: never;
    query: {
        aliases: Array<string>;
    };
    url: '/v3/connect/profile/publicUserProfiles';
};

export type GetPublicUserProfilesResponses = {
    /**
     * OK
     */
    200: AccountFullPublicProfilesSchema;
};

export type GetPublicUserProfilesResponse = GetPublicUserProfilesResponses[keyof GetPublicUserProfilesResponses];

export type GetPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/connect/profile/permissions';
};

export type GetPermissionsResponses = {
    /**
     * OK
     */
    200: ConnectPermissionsSchema;
};

export type GetPermissionsResponse = GetPermissionsResponses[keyof GetPermissionsResponses];

export type GetExchangeRateData = {
    body?: never;
    path: {
        currencyCode: 'AED' | 'AFN' | 'ALL' | 'AMD' | 'ANG' | 'AOA' | 'ARS' | 'AUD' | 'AWG' | 'AZN' | 'BAM' | 'BBD' | 'BDT' | 'BGN' | 'BHD' | 'BIF' | 'BMD' | 'BND' | 'BOB' | 'BRL' | 'BSD' | 'BTC' | 'BTN' | 'BWP' | 'BYN' | 'BYR' | 'BZD' | 'CAD' | 'CDF' | 'CHF' | 'CLF' | 'CLP' | 'CNY' | 'CNH' | 'COP' | 'CRC' | 'CUC' | 'CUP' | 'CVE' | 'CZK' | 'DJF' | 'DKK' | 'DOP' | 'DZD' | 'EGP' | 'ERN' | 'ETB' | 'EUR' | 'FJD' | 'FKP' | 'GBP' | 'GEL' | 'GGP' | 'GHS' | 'GIP' | 'GMD' | 'GNF' | 'GTQ' | 'GYD' | 'HKD' | 'HNL' | 'HRK' | 'HTG' | 'HUF' | 'IDR' | 'ILS' | 'IMP' | 'INR' | 'IQD' | 'IRR' | 'ISK' | 'JEP' | 'JMD' | 'JOD' | 'JPY' | 'KES' | 'KGS' | 'KHR' | 'KMF' | 'KPW' | 'KRW' | 'KWD' | 'KYD' | 'KZT' | 'LAK' | 'LBP' | 'LKR' | 'LRD' | 'LSL' | 'LTL' | 'LVL' | 'LYD' | 'MAD' | 'MDL' | 'MGA' | 'MKD' | 'MMK' | 'MNT' | 'MOP' | 'MRU' | 'MUR' | 'MVR' | 'MWK' | 'MXN' | 'MYR' | 'MZN' | 'NAD' | 'NGN' | 'NIO' | 'NOK' | 'NPR' | 'NZD' | 'OMR' | 'PAB' | 'PEN' | 'PGK' | 'PHP' | 'PKR' | 'PLN' | 'PYG' | 'QAR' | 'RON' | 'RSD' | 'RUB' | 'RWF' | 'SAR' | 'SBD' | 'SCR' | 'SDG' | 'SEK' | 'SGD' | 'SHP' | 'SLE' | 'SLL' | 'SOS' | 'SRD' | 'STD' | 'SVC' | 'SYP' | 'SZL' | 'THB' | 'TJS' | 'TMT' | 'TND' | 'TOP' | 'TRY' | 'TTD' | 'TWD' | 'TZS' | 'UAH' | 'UGX' | 'USD' | 'UYU' | 'UZS' | 'VES' | 'VND' | 'VUV' | 'WST' | 'XAF' | 'XAG' | 'XAU' | 'XCD' | 'XDR' | 'XOF' | 'XPF' | 'YER' | 'ZAR' | 'ZMK' | 'ZMW' | 'ZWL';
    };
    query?: never;
    url: '/v3/connect/exchangeRate/{currencyCode}';
};

export type GetExchangeRateResponses = {
    /**
     * OK
     */
    200: MiscExchangeRateSchema;
};

export type GetExchangeRateResponse = GetExchangeRateResponses[keyof GetExchangeRateResponses];

export type GetDepositAddressData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/connect/wallet/address';
};

export type GetDepositAddressResponses = {
    /**
     * OK
     */
    200: WalletAddressSchema;
};

export type GetDepositAddressResponse = GetDepositAddressResponses[keyof GetDepositAddressResponses];

export type GetBalancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/connect/wallet/balances';
};

export type GetBalancesResponses = {
    /**
     * OK
     */
    200: WalletBalancesSchema;
};

export type GetBalancesResponse = GetBalancesResponses[keyof GetBalancesResponses];

export type GetSpendableBalancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/connect/wallet/spendableBalances';
};

export type GetSpendableBalancesResponses = {
    /**
     * OK
     */
    200: WalletSpendableBalancesSchema;
};

export type GetSpendableBalancesResponse = GetSpendableBalancesResponses[keyof GetSpendableBalancesResponses];

export type PayData = {
    body: {
        exchangeRateVersion?: string;
        instrumentCurrencyCode: 'MNEE' | 'BSV';
        denominationCurrencyCode?: 'AED' | 'AFN' | 'ALL' | 'AMD' | 'ANG' | 'AOA' | 'ARS' | 'AUD' | 'AWG' | 'AZN' | 'BAM' | 'BBD' | 'BDT' | 'BGN' | 'BHD' | 'BIF' | 'BMD' | 'BND' | 'BOB' | 'BRL' | 'BSD' | 'BTC' | 'BTN' | 'BWP' | 'BYN' | 'BYR' | 'BZD' | 'CAD' | 'CDF' | 'CHF' | 'CLF' | 'CLP' | 'CNY' | 'CNH' | 'COP' | 'CRC' | 'CUC' | 'CUP' | 'CVE' | 'CZK' | 'DJF' | 'DKK' | 'DOP' | 'DZD' | 'EGP' | 'ERN' | 'ETB' | 'EUR' | 'FJD' | 'FKP' | 'GBP' | 'GEL' | 'GGP' | 'GHS' | 'GIP' | 'GMD' | 'GNF' | 'GTQ' | 'GYD' | 'HKD' | 'HNL' | 'HRK' | 'HTG' | 'HUF' | 'IDR' | 'ILS' | 'IMP' | 'INR' | 'IQD' | 'IRR' | 'ISK' | 'JEP' | 'JMD' | 'JOD' | 'JPY' | 'KES' | 'KGS' | 'KHR' | 'KMF' | 'KPW' | 'KRW' | 'KWD' | 'KYD' | 'KZT' | 'LAK' | 'LBP' | 'LKR' | 'LRD' | 'LSL' | 'LTL' | 'LVL' | 'LYD' | 'MAD' | 'MDL' | 'MGA' | 'MKD' | 'MMK' | 'MNT' | 'MOP' | 'MRU' | 'MUR' | 'MVR' | 'MWK' | 'MXN' | 'MYR' | 'MZN' | 'NAD' | 'NGN' | 'NIO' | 'NOK' | 'NPR' | 'NZD' | 'OMR' | 'PAB' | 'PEN' | 'PGK' | 'PHP' | 'PKR' | 'PLN' | 'PYG' | 'QAR' | 'RON' | 'RSD' | 'RUB' | 'RWF' | 'SAR' | 'SBD' | 'SCR' | 'SDG' | 'SEK' | 'SGD' | 'SHP' | 'SLE' | 'SLL' | 'SOS' | 'SRD' | 'STD' | 'SVC' | 'SYP' | 'SZL' | 'THB' | 'TJS' | 'TMT' | 'TND' | 'TOP' | 'TRY' | 'TTD' | 'TWD' | 'TZS' | 'UAH' | 'UGX' | 'USD' | 'UYU' | 'UZS' | 'VES' | 'VND' | 'VUV' | 'WST' | 'XAF' | 'XAG' | 'XAU' | 'XCD' | 'XDR' | 'XOF' | 'XPF' | 'YER' | 'ZAR' | 'ZMK' | 'ZMW' | 'ZWL';
        note?: string;
        attachment?: {
            format: 'hex' | 'base64' | 'json' | 'hexArray';
            value?: {
                [key: string]: never;
            } | Array<string> | string;
        };
        receivers?: Array<{
            sendAmount: number;
            destination: string;
            tags?: Array<string>;
        }> | Array<{
            sendAmount: number;
            destination: string;
            tags?: Array<string>;
        }>;
    };
    path?: never;
    query?: never;
    url: '/v3/connect/wallet/pay';
};

export type PayResponses = {
    /**
     * OK
     */
    200: WalletTransactionRecordSchema;
};

export type PayResponse = PayResponses[keyof PayResponses];

export type GetPaymentDetailsData = {
    body?: never;
    path?: never;
    query: {
        transactionId: string;
    };
    url: '/v3/connect/wallet/payment';
};

export type GetPaymentDetailsResponses = {
    /**
     * OK
     */
    200: WalletTransactionRecordSchema;
};

export type GetPaymentDetailsResponse = GetPaymentDetailsResponses[keyof GetPaymentDetailsResponses];

export type GetItemsInventoryData = {
    body: {
        from?: number;
        to?: number;
        collectionIds?: Array<string>;
        searchString?: string;
        groupingValue?: string;
        fetchAttributes?: boolean;
        sort?: 'name';
        order?: 'asc' | 'desc';
        attributes?: Array<{
            name: string;
            displayType: 'string' | 'number';
            operation?: 'equal' | 'includes' | 'matches' | 'greater' | 'lower' | 'greaterOrEqual' | 'lowerOrEqual';
            value?: string | number;
            values?: Array<string | number>;
        }>;
        group?: boolean;
        externalId?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/connect/items/inventory';
};

export type GetItemsInventoryResponses = {
    /**
     * OK
     */
    200: ItemsItemsSchema;
};

export type GetItemsInventoryResponse = GetItemsInventoryResponses[keyof GetItemsInventoryResponses];

export type GetV3FriendsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/friends/';
};

export type GetV3FriendsResponses = {
    /**
     * OK
     */
    200: AccountProfilesSchema;
};

export type GetV3FriendsResponse = GetV3FriendsResponses[keyof GetV3FriendsResponses];

export type PostV3FriendsData = {
    body: {
        alias: string;
    };
    path?: never;
    query?: never;
    url: '/v3/friends/';
};

export type PostV3FriendsResponses = {
    /**
     * OK
     */
    200: AccountProfileApiDefinition;
};

export type PostV3FriendsResponse = PostV3FriendsResponses[keyof PostV3FriendsResponses];

export type DeleteV3FriendsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/friends/{id}';
};

export type DeleteV3FriendsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPaymentRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/paymentRequests/';
};

export type GetPaymentRequestsResponses = {
    /**
     * OK
     */
    200: PaymentRequestPrivatePaymentRequestsSchema;
};

export type GetPaymentRequestsResponse = GetPaymentRequestsResponses[keyof GetPaymentRequestsResponses];

export type CreatePaymentRequestData = {
    body: {
        product: {
            name: string;
            description?: string;
            longDescription?: string;
            imageUrl?: string;
        };
        instrumentCurrencyCode: 'MNEE' | 'BSV';
        denominationCurrencyCode?: 'AED' | 'AFN' | 'ALL' | 'AMD' | 'ANG' | 'AOA' | 'ARS' | 'AUD' | 'AWG' | 'AZN' | 'BAM' | 'BBD' | 'BDT' | 'BGN' | 'BHD' | 'BIF' | 'BMD' | 'BND' | 'BOB' | 'BRL' | 'BSD' | 'BTC' | 'BTN' | 'BWP' | 'BYN' | 'BYR' | 'BZD' | 'CAD' | 'CDF' | 'CHF' | 'CLF' | 'CLP' | 'CNY' | 'CNH' | 'COP' | 'CRC' | 'CUC' | 'CUP' | 'CVE' | 'CZK' | 'DJF' | 'DKK' | 'DOP' | 'DZD' | 'EGP' | 'ERN' | 'ETB' | 'EUR' | 'FJD' | 'FKP' | 'GBP' | 'GEL' | 'GGP' | 'GHS' | 'GIP' | 'GMD' | 'GNF' | 'GTQ' | 'GYD' | 'HKD' | 'HNL' | 'HRK' | 'HTG' | 'HUF' | 'IDR' | 'ILS' | 'IMP' | 'INR' | 'IQD' | 'IRR' | 'ISK' | 'JEP' | 'JMD' | 'JOD' | 'JPY' | 'KES' | 'KGS' | 'KHR' | 'KMF' | 'KPW' | 'KRW' | 'KWD' | 'KYD' | 'KZT' | 'LAK' | 'LBP' | 'LKR' | 'LRD' | 'LSL' | 'LTL' | 'LVL' | 'LYD' | 'MAD' | 'MDL' | 'MGA' | 'MKD' | 'MMK' | 'MNT' | 'MOP' | 'MRU' | 'MUR' | 'MVR' | 'MWK' | 'MXN' | 'MYR' | 'MZN' | 'NAD' | 'NGN' | 'NIO' | 'NOK' | 'NPR' | 'NZD' | 'OMR' | 'PAB' | 'PEN' | 'PGK' | 'PHP' | 'PKR' | 'PLN' | 'PYG' | 'QAR' | 'RON' | 'RSD' | 'RUB' | 'RWF' | 'SAR' | 'SBD' | 'SCR' | 'SDG' | 'SEK' | 'SGD' | 'SHP' | 'SLE' | 'SLL' | 'SOS' | 'SRD' | 'STD' | 'SVC' | 'SYP' | 'SZL' | 'THB' | 'TJS' | 'TMT' | 'TND' | 'TOP' | 'TRY' | 'TTD' | 'TWD' | 'TZS' | 'UAH' | 'UGX' | 'USD' | 'UYU' | 'UZS' | 'VES' | 'VND' | 'VUV' | 'WST' | 'XAF' | 'XAG' | 'XAU' | 'XCD' | 'XDR' | 'XOF' | 'XPF' | 'YER' | 'ZAR' | 'ZMK' | 'ZMW' | 'ZWL';
        receivers: Array<{
            sendAmount: number;
            destination: string;
            tags?: Array<string>;
        }>;
        requestedUserData?: Array<'paymail' | 'email' | 'phoneNumber'>;
        paymentMethods?: Array<'onChain' | 'externalPaymentProcessor'>;
        redirectUrl?: string;
        notifications?: {
            webhook?: {
                webhookUrl: string;
                customParameters?: {
                    [key: string]: never;
                };
            };
            email?: string;
        };
        totalUnits?: number;
        /**
         * @deprecated
         */
        expirationInSeconds?: number;
        expirationType?: string;
        /**
         * @deprecated
         */
        expiresAt?: string;
        enabledAt?: string;
        priceBeforeDiscount?: number;
        shop?: {
            collectionId: string;
            packOrder: number;
            collectionOrder: number;
        };
    };
    path?: never;
    query?: never;
    url: '/v3/paymentRequests/';
};

export type CreatePaymentRequestResponses = {
    /**
     * OK
     */
    200: PaymentRequestPrivatePaymentRequestSchema;
};

export type CreatePaymentRequestResponse = CreatePaymentRequestResponses[keyof CreatePaymentRequestResponses];

export type DeletePaymentRequestData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/paymentRequests/{id}';
};

export type DeletePaymentRequestResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPaymentRequestData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/paymentRequests/{id}';
};

export type GetPaymentRequestResponses = {
    /**
     * OK
     */
    200: PaymentRequestPrivatePaymentRequestSchema;
};

export type GetPaymentRequestResponse = GetPaymentRequestResponses[keyof GetPaymentRequestResponses];

export type UpdatePaymentRequestData = {
    body: {
        product?: {
            name?: string;
            description?: string;
            longDescription?: string;
            imageUrl?: string;
        };
        redirectUrl?: string;
        notifications?: {
            webhook?: {
                webhookUrl?: string;
                customParameters?: {
                    [key: string]: never;
                };
            };
            email?: string;
        };
        /**
         * @deprecated
         */
        expirationInSeconds?: number;
        expiresAt?: string;
        decreaseRemainingUnits?: number;
        priceBeforeDiscount?: number | null;
        shop?: {
            collectionId: string;
            packOrder: number;
            collectionOrder: number;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/paymentRequests/{id}';
};

export type UpdatePaymentRequestResponses = {
    /**
     * OK
     */
    200: PaymentRequestPrivatePaymentRequestSchema;
};

export type UpdatePaymentRequestResponse = UpdatePaymentRequestResponses[keyof UpdatePaymentRequestResponses];

export type GetPaymentRequestsPublicInfoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        referenceId?: string;
    };
    url: '/v3/paymentRequests/public/{id}';
};

export type GetPaymentRequestsPublicInfoResponses = {
    /**
     * OK
     */
    200: PaymentRequestPaymentRequestSchema;
};

export type GetPaymentRequestsPublicInfoResponse = GetPaymentRequestsPublicInfoResponses[keyof GetPaymentRequestsPublicInfoResponses];

export type GetPaymentRequestsPublicStatsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/paymentRequests/public/stats/{id}';
};

export type GetPaymentRequestsPublicStatsResponses = {
    /**
     * OK
     */
    200: PaymentRequestPaymentRequestStatsSchema;
};

export type GetPaymentRequestsPublicStatsResponse = GetPaymentRequestsPublicStatsResponses[keyof GetPaymentRequestsPublicStatsResponses];

export type GetItemCreationOrderData = {
    body?: never;
    path: {
        itemCreationOrderId: string;
    };
    query?: never;
    url: '/v3/itemCreationOrder/{itemCreationOrderId}';
};

export type GetItemCreationOrderResponses = {
    /**
     * OK
     */
    200: ItemsItemCreationOrderSchema;
};

export type GetItemCreationOrderResponse = GetItemCreationOrderResponses[keyof GetItemCreationOrderResponses];

export type GetItemsData = {
    body?: never;
    path: {
        itemCreationOrderId: string;
    };
    query?: never;
    url: '/v3/itemCreationOrder/{itemCreationOrderId}/items';
};

export type GetItemsResponses = {
    /**
     * OK
     */
    200: ItemsItemsSchema;
};

export type GetItemsResponse = GetItemsResponses[keyof GetItemsResponses];

export type CreateItemCreationOrderData = {
    body: {
        uid?: string;
        itemCreationOrderType: 'collection' | 'collectionItem';
        items?: Array<{
            description?: string;
            name: string;
            groupingValue?: string;
            color?: string;
            mediaDetails: {
                image: {
                    url: string;
                    imageHighResUrl?: string;
                    contentType: 'image/png' | 'image/jpg' | 'image/jpeg' | 'image/webp';
                };
                multimedia?: {
                    url: string;
                    contentType: string;
                };
            };
            user?: string;
            quantity?: number;
            rarity?: string;
            attributes?: Array<{
                name: string;
                displayType: string;
                value?: number | string;
            }>;
            actions?: Array<{
                name: string;
                description: string;
                url: string;
                enabled?: boolean;
            }>;
            royalties?: Array<{
                type: 'paymail' | 'address' | 'script';
                percentage: number;
                destination: string;
            }>;
            externalId?: string;
        }> | [
            {
                description?: string;
                name: string;
                groupingValue?: string;
                color?: string;
                mediaDetails: {
                    image: {
                        url: string;
                        imageHighResUrl?: string;
                        contentType: 'image/png' | 'image/jpg' | 'image/jpeg' | 'image/webp';
                    };
                    multimedia?: {
                        url: string;
                        contentType: string;
                    };
                };
                user?: string;
                totalQuantity?: number;
            }
        ];
        referencedCollection?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/itemCreationOrder/';
};

export type CreateItemCreationOrderResponses = {
    /**
     * OK
     */
    200: ItemsItemCreationOrderSchema;
};

export type CreateItemCreationOrderResponse = CreateItemCreationOrderResponses[keyof CreateItemCreationOrderResponses];

export type AddItemsToItemCreationOrderData = {
    body: {
        itemCreationOrderType?: 'collection' | 'collectionItem';
        items?: Array<{
            description?: string;
            name: string;
            groupingValue?: string;
            color?: string;
            mediaDetails: {
                image: {
                    url: string;
                    imageHighResUrl?: string;
                    contentType: 'image/png' | 'image/jpg' | 'image/jpeg' | 'image/webp';
                };
                multimedia?: {
                    url: string;
                    contentType: string;
                };
            };
            user?: string;
            quantity?: number;
            rarity?: string;
            attributes?: Array<{
                name: string;
                displayType: string;
                value?: number | string;
            }>;
            actions?: Array<{
                name: string;
                description: string;
                url: string;
                enabled?: boolean;
            }>;
            royalties?: Array<{
                type: 'paymail' | 'address' | 'script';
                percentage: number;
                destination: string;
            }>;
            externalId?: string;
        }> | Array<{
            description?: string;
            name: string;
            groupingValue?: string;
            color?: string;
            mediaDetails: {
                image: {
                    url: string;
                    imageHighResUrl?: string;
                    contentType: 'image/png' | 'image/jpg' | 'image/jpeg' | 'image/webp';
                };
                multimedia?: {
                    url: string;
                    contentType: string;
                };
            };
            user?: string;
            totalQuantity?: number;
        }>;
    };
    path: {
        itemCreationOrderId: string;
    };
    query?: never;
    url: '/v3/itemCreationOrder/{itemCreationOrderId}/add';
};

export type AddItemsToItemCreationOrderResponses = {
    /**
     * OK
     */
    200: ItemsItemCreationOrderSchema;
};

export type AddItemsToItemCreationOrderResponse = AddItemsToItemCreationOrderResponses[keyof AddItemsToItemCreationOrderResponses];

export type CommitItemCreationOrderData = {
    body?: never;
    path: {
        itemCreationOrderId: string;
    };
    query?: never;
    url: '/v3/itemCreationOrder/{itemCreationOrderId}/commit';
};

export type CommitItemCreationOrderResponses = {
    /**
     * OK
     */
    200: ItemsItemCreationOrderSchema;
};

export type CommitItemCreationOrderResponse = CommitItemCreationOrderResponses[keyof CommitItemCreationOrderResponses];

export type CreateBatchData = {
    body: {
        itemCreationOrderId: string;
    };
    path?: never;
    query?: never;
    url: '/v3/itemCreationOrder/createBatch';
};

export type CreateBatchResponses = {
    /**
     * OK
     */
    200: ItemsItemCreationOrderSchema;
};

export type CreateBatchResponse = CreateBatchResponses[keyof CreateBatchResponses];

export type IssueItemsData = {
    body: {
        uid?: string;
        itemCreationOrderType: 'collection' | 'collectionItem';
        items?: Array<{
            description?: string;
            name: string;
            groupingValue?: string;
            color?: string;
            mediaDetails: {
                image: {
                    url: string;
                    imageHighResUrl?: string;
                    contentType: 'image/png' | 'image/jpg' | 'image/jpeg' | 'image/webp';
                };
                multimedia?: {
                    url: string;
                    contentType: string;
                };
            };
            user?: string;
            quantity?: number;
            rarity?: string;
            attributes?: Array<{
                name: string;
                displayType: string;
                value?: number | string;
            }>;
            actions?: Array<{
                name: string;
                description: string;
                url: string;
                enabled?: boolean;
            }>;
            royalties?: Array<{
                type: 'paymail' | 'address' | 'script';
                percentage: number;
                destination: string;
            }>;
            externalId?: string;
        }> | [
            {
                description?: string;
                name: string;
                groupingValue?: string;
                color?: string;
                mediaDetails: {
                    image: {
                        url: string;
                        imageHighResUrl?: string;
                        contentType: 'image/png' | 'image/jpg' | 'image/jpeg' | 'image/webp';
                    };
                    multimedia?: {
                        url: string;
                        contentType: string;
                    };
                };
                user?: string;
                totalQuantity?: number;
            }
        ];
        referencedCollection?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/itemCreationOrder/issueItems';
};

export type IssueItemsResponses = {
    /**
     * OK
     */
    200: ItemsItemCreationOrderSchema;
};

export type IssueItemsResponse = IssueItemsResponses[keyof IssueItemsResponses];

export type BurnAndCreateData = {
    body: {
        burn: {
            origins: Array<string>;
        };
        issue?: {
            items?: Array<{
                description?: string;
                name: string;
                groupingValue?: string;
                color?: string;
                mediaDetails: {
                    image: {
                        url: string;
                        imageHighResUrl?: string;
                        contentType: 'image/png' | 'image/jpg' | 'image/jpeg' | 'image/webp';
                    };
                    multimedia?: {
                        url: string;
                        contentType: string;
                    };
                };
                user?: string;
                quantity?: number;
                rarity?: string;
                attributes?: Array<{
                    name: string;
                    displayType: string;
                    value?: number | string;
                }>;
                actions?: Array<{
                    name: string;
                    description: string;
                    url: string;
                    enabled?: boolean;
                }>;
                royalties?: Array<{
                    type: 'paymail' | 'address' | 'script';
                    percentage: number;
                    destination: string;
                }>;
                externalId?: string;
            }>;
            referencedCollection: string;
            uid?: string;
            itemCreationOrderType?: 'collectionItem';
        };
    };
    path?: never;
    query?: never;
    url: '/v3/itemCreationOrder/burnAndCreate';
};

export type BurnAndCreateResponses = {
    /**
     * TODO
     */
    200: {
        '[[TODO]]'?: string;
    };
};

export type BurnAndCreateResponse = BurnAndCreateResponses[keyof BurnAndCreateResponses];

export type PostV3WalletItemsInventoryData = {
    body: {
        from?: number;
        to?: number;
        /**
         * @deprecated
         */
        collectionId?: string;
        collectionIds?: Array<string>;
        searchString?: string;
        groupingValue?: string;
        fetchAttributes?: boolean;
        sort?: 'name';
        order?: 'asc' | 'desc';
        attributes?: Array<{
            name: string;
            displayType: 'string' | 'number';
            operation?: 'equal' | 'includes' | 'matches' | 'greater' | 'lower' | 'greaterOrEqual' | 'lowerOrEqual';
            value?: string | number;
            values?: Array<string | number>;
        }>;
        appId?: string;
        group?: boolean;
        externalId?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/wallet/items/inventory';
};

export type PostV3WalletItemsInventoryResponses = {
    /**
     * OK
     */
    200: ItemsItemsSchema;
};

export type PostV3WalletItemsInventoryResponse = PostV3WalletItemsInventoryResponses[keyof PostV3WalletItemsInventoryResponses];

export type GetV3WalletItemsInventoryStatsData = {
    body?: never;
    path?: never;
    query?: {
        groupingValue?: string;
        applicationId?: string;
    };
    url: '/v3/wallet/items/inventory/stats';
};

export type GetV3WalletItemsInventoryStatsResponses = {
    /**
     * OK
     */
    200: ItemsItemStatsSchema;
};

export type GetV3WalletItemsInventoryStatsResponse = GetV3WalletItemsInventoryStatsResponses[keyof GetV3WalletItemsInventoryStatsResponses];

export type GetV3WalletItemsInventoryApplicationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/wallet/items/inventory/applications';
};

export type GetV3WalletItemsInventoryApplicationsResponses = {
    /**
     * OK
     */
    200: ApplicationApplicationsSchema;
};

export type GetV3WalletItemsInventoryApplicationsResponse = GetV3WalletItemsInventoryApplicationsResponses[keyof GetV3WalletItemsInventoryApplicationsResponses];

export type GetV3WalletItemsHistoryApplicationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/wallet/items/history/applications';
};

export type GetV3WalletItemsHistoryApplicationsResponses = {
    /**
     * OK
     */
    200: ApplicationApplicationsSchema;
};

export type GetV3WalletItemsHistoryApplicationsResponse = GetV3WalletItemsHistoryApplicationsResponses[keyof GetV3WalletItemsHistoryApplicationsResponses];

export type GetV3WalletItemsTopTradedData = {
    body?: never;
    path?: never;
    query?: {
        applicationId?: string;
        count?: number;
    };
    url: '/v3/wallet/items/topTraded';
};

export type GetV3WalletItemsTopTradedResponses = {
    /**
     * OK
     */
    200: ItemsItemsSchema;
};

export type GetV3WalletItemsTopTradedResponse = GetV3WalletItemsTopTradedResponses[keyof GetV3WalletItemsTopTradedResponses];

export type GetV3WalletItemsTradeHistoryData = {
    body?: never;
    path?: never;
    query: {
        fromDate: string;
        toDate: string;
        groupingValue: string;
    };
    url: '/v3/wallet/items/tradeHistory';
};

export type GetV3WalletItemsTradeHistoryResponses = {
    /**
     * OK
     */
    200: ItemsItemTradeHistorySchema;
};

export type GetV3WalletItemsTradeHistoryResponse = GetV3WalletItemsTradeHistoryResponses[keyof GetV3WalletItemsTradeHistoryResponses];

export type GetV3WalletItemsMetricsData = {
    body?: never;
    path?: never;
    query?: {
        groupingValue?: string;
        applicationId?: string;
    };
    url: '/v3/wallet/items/metrics';
};

export type GetV3WalletItemsMetricsResponses = {
    /**
     * OK
     */
    200: ItemsItemMetricsSchema;
};

export type GetV3WalletItemsMetricsResponse = GetV3WalletItemsMetricsResponses[keyof GetV3WalletItemsMetricsResponses];

export type PostV3WalletItemsSendData = {
    body: {
        destinationsWithOrigins: Array<{
            destination: string;
            origins: Array<string>;
        }>;
    };
    path?: never;
    query?: never;
    url: '/v3/wallet/items/send';
};

export type PostV3WalletItemsSendResponses = {
    /**
     * TODO
     */
    200: {
        '[[TODO]]'?: string;
    };
};

export type PostV3WalletItemsSendResponse = PostV3WalletItemsSendResponses[keyof PostV3WalletItemsSendResponses];

export type PostV3WalletItemsLockByOriginData = {
    body?: never;
    path: {
        origin: string;
    };
    query?: never;
    url: '/v3/wallet/items/lock/{origin}';
};

export type PostV3WalletItemsLockByOriginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostV3WalletItemsUnlockByOriginData = {
    body?: never;
    path: {
        origin: string;
    };
    query?: never;
    url: '/v3/wallet/items/unlock/{origin}';
};

export type PostV3WalletItemsUnlockByOriginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetV3WalletItemsLockedData = {
    body?: never;
    path?: never;
    query?: {
        from?: number;
        to?: number;
        fetchAttributes?: boolean;
        /**
         * When set, only locked items whose owner (referencedUserId) matches this HandCash user id are returned.
         */
        userId?: string;
    };
    url: '/v3/wallet/items/locked';
};

export type GetV3WalletItemsLockedResponses = {
    /**
     * OK
     */
    200: ItemsItemsSchema;
};

export type GetV3WalletItemsLockedResponse = GetV3WalletItemsLockedResponses[keyof GetV3WalletItemsLockedResponses];

export type GetV3WalletItemsCollectionsData = {
    body?: never;
    path?: never;
    query?: {
        appId?: string;
    };
    url: '/v3/wallet/items/collections';
};

export type GetV3WalletItemsCollectionsResponses = {
    /**
     * OK
     */
    200: ItemsCollectionsSchema;
};

export type GetV3WalletItemsCollectionsResponse = GetV3WalletItemsCollectionsResponses[keyof GetV3WalletItemsCollectionsResponses];

export type GetV3WalletItemsCollectionByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/wallet/items/collection/{id}';
};

export type GetV3WalletItemsCollectionByIdResponses = {
    /**
     * OK
     */
    200: ItemsCollectionSchema;
};

export type GetV3WalletItemsCollectionByIdResponse = GetV3WalletItemsCollectionByIdResponses[keyof GetV3WalletItemsCollectionByIdResponses];

export type PutV3WalletItemsCollectionByCollectionIdData = {
    body?: never;
    path: {
        collectionId: string;
    };
    query?: never;
    url: '/v3/wallet/items/collection/{collectionId}';
};

export type PutV3WalletItemsCollectionByCollectionIdResponses = {
    /**
     * OK
     */
    200: ItemsCollectionSchema;
};

export type PutV3WalletItemsCollectionByCollectionIdResponse = PutV3WalletItemsCollectionByCollectionIdResponses[keyof PutV3WalletItemsCollectionByCollectionIdResponses];

export type PostV3WalletItemsHistoryData = {
    body: {
        from?: number;
        to?: number;
        searchString?: string;
        groupingValue?: string;
        sort?: 'priceInUSD' | 'itemName' | 'createdAt';
        order?: 'asc' | 'desc';
        attributes?: Array<{
            name: string;
            displayType: 'string' | 'number';
            operation?: 'equal' | 'includes' | 'matches' | 'greater' | 'lower' | 'greaterOrEqual' | 'lowerOrEqual';
            value?: string | number;
            values?: Array<string | number>;
        }>;
        collectionIds?: Array<string>;
        appIds?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/v3/wallet/items/history';
};

export type PostV3WalletItemsHistoryResponses = {
    /**
     * OK
     */
    200: ItemsItemTransferSchema;
};

export type PostV3WalletItemsHistoryResponse = PostV3WalletItemsHistoryResponses[keyof PostV3WalletItemsHistoryResponses];

export type GetV3WalletItemsByOriginData = {
    body?: never;
    path: {
        origin: string;
    };
    query?: never;
    url: '/v3/wallet/items/{origin}';
};

export type GetV3WalletItemsByOriginResponses = {
    /**
     * OK
     */
    200: ItemsItemSchema;
};

export type GetV3WalletItemsByOriginResponse = GetV3WalletItemsByOriginResponses[keyof GetV3WalletItemsByOriginResponses];

export type GetV3WalletItemsDefinitionByGroupingValueData = {
    body?: never;
    path: {
        groupingValue: string;
    };
    query?: never;
    url: '/v3/wallet/items/definition/{groupingValue}';
};

export type GetV3WalletItemsDefinitionByGroupingValueResponses = {
    /**
     * OK
     */
    200: ItemsItemSchema;
};

export type GetV3WalletItemsDefinitionByGroupingValueResponse = GetV3WalletItemsDefinitionByGroupingValueResponses[keyof GetV3WalletItemsDefinitionByGroupingValueResponses];

export type ClientOptions = {
    baseUrl: 'https://cloud.handcash.io' | (string & {});
};